In [1]:
import numpy as np


In [2]:
benimDizi = np.arange(0,15)

In [3]:
benimDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
benimDizi[0]

0

In [5]:
benimDizi[3:8]#3 ve 8 arası

array([3, 4, 5, 6, 7])

In [6]:
benimDizi[3:8] = -5

In [7]:
benimDizi

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [8]:
benimDizi[:] = 0

In [9]:
benimDizi

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])