In [2]:
import numpy as np


## random

In [6]:
np.random.randn(8)

array([ 0.4385557 , -0.77868371, -0.56518014,  0.7507593 ,  0.9853573 ,
       -0.4748095 ,  1.88234027,  0.0800696 ])

In [7]:
np.random.randn(4,4)

array([[ 0.12165449, -1.15384146, -1.23771389, -2.1137121 ],
       [-1.70145082, -1.8005704 ,  0.44180492, -1.70688369],
       [ 1.27232885,  0.02984225, -0.94447247, -0.66145621],
       [ 1.28507998, -0.0432567 , -0.66797647, -0.91672398]])

In [8]:
np.random.randint(1,10)

3

In [9]:
np.random.randint(1,10,5)

array([4, 7, 8, 9, 7])

## numpy dizi methodları